SELECT 

CAST(string_field_0 as INTEGER) as id_ioc,
string_field_1 as english_name,
string_field_2 as latin_name,
string_field_3 as hbw_birdlife_international_v9_1,
string_field_4 as ioc_world_bird_list_v15_1,
string_field_5 as ebird_clements_v2024b,
string_field_6 as avilist_v1_2025,
string_field_7 as order_name,
string_field_8 as family_ioc_15_1,
string_field_9 as family_clements_v2024b,
string_field_10 as family_hbw_birdlife_v9_1_2024,
string_field_11 as family_avilist_v1_2025,
string_field_12 as genus,
string_field_13 as species,
string_field_14 as source,
string_field_15 as iucn_red_list_category_2024,
CASE when string_field_16 = '0' then FALSE
when string_field_16 = '1' then True
else NULL
end  as rr,
-- CAST(string_field_16 as INteger) as rr
-- CAST(string_field_16 as Boolean) as rr,
CAST(string_field_17 as INTEGER) as isl,
string_field_18 as rlm,
CAST(string_field_19 as INTEGER) as lat,
string_field_20 as female_minmass,
-- CAST(string_field_21 as FLOAT) as female_maxmass,
-- CAST(string_field_22 as FLOAT) as male_minmass,
-- CAST(string_field_23 as FLOAT) as male_maxmass,
-- CAST(string_field_24 as FLOAT) as unsexed_minmass,
-- CAST(string_field_25 as FLOAT) as unsexed_maxmass,
-- CAST(string_field_26 as FLOAT) as average_mass,
-- CAST(string_field_27 as FLOAT) as xmin,
-- CAST(string_field_28 as FLOAT) as normmin,
-- CAST(string_field_29 as FLOAT) as elevational_range,
-- CAST(string_field_30 as FLOAT) as normmax,
-- CAST(string_field_31 as FLOAT) as xmax,
-- CAST(string_field_32 as FLOAT) as f,
-- CAST(string_field_33 as FLOAT) as bm,
-- CAST(string_field_34 as FLOAT) as wd,
-- CAST(string_field_35 as FLOAT) as sh,
-- CAST(string_field_36 as FLOAT) as sv,
-- CAST(string_field_37 as FLOAT) as g,
-- CAST(string_field_38 as FLOAT) as pl,
-- CAST(string_field_39 as FLOAT) as r,
-- CAST(string_field_40 as FLOAT) as d,
-- CAST(string_field_41 as FLOAT) as a,
-- CAST(string_field_42 as FLOAT) as rv,
-- CAST(string_field_43 as FLOAT) as c,
-- CAST(string_field_44 as FLOAT) as w,
-- CAST(string_field_45 as FLOAT) as se,
-- CAST(string_field_46 as FLOAT) as o,
-- string_field_47 as o_desc,
-- string_field_48 as primary_habitat,
-- string_field_49 as hb,
-- string_field_50 as primary_diet,
-- CAST(string_field_51 as FLOAT) as in_wt,
-- CAST(string_field_52 as FLOAT) as fr_wt,
-- CAST(string_field_53 as FLOAT) as ne_wt,
-- CAST(string_field_54 as FLOAT) as se_wt,
-- CAST(string_field_55 as FLOAT) as ve_wt,
-- CAST(string_field_56 as FLOAT) as fi_wt,
-- CAST(string_field_57 as FLOAT) as sc_wt,
-- CAST(string_field_58 as FLOAT) as pl_wt,
-- CAST(string_field_59 as FLOAT) as ms_wt,
-- CAST(string_field_60 as FLOAT) as sum_wt,
-- string_field_61 as o_desc,
-- string_field_62 as db,
-- string_field_63 as diet_lit,
-- CAST(string_field_64 as FLOAT) as esi,
-- string_field_65 as social_1,
-- string_field_66 as social_2,
-- string_field_67 as social_3,
-- string_field_68 as social_4,
-- string_field_69 as social_5,
-- string_field_70 as social_6,
-- CAST(string_field_71 as FLOAT) as mono,
-- CAST(string_field_72 as FLOAT) as poly,
-- CAST(string_field_73 as FLOAT) as coop,
-- string_field_74 as nest_type,
-- string_field_75 as nest_sbs,
-- CAST(string_field_76 as FLOAT) as brd1,
-- CAST(string_field_77 as FLOAT) as brd2,
-- CAST(string_field_78 as FLOAT) as clutch_min,
-- CAST(string_field_79 as FLOAT) as clutch_max,
-- string_field_80 as incu_sex,
-- CAST(string_field_81 as FLOAT) as incu1,
-- CAST(string_field_82 as FLOAT) as incu2,
-- CAST(string_field_83 as FLOAT) as fldg1,
-- CAST(string_field_84 as FLOAT) as fldg2,
-- CAST(string_field_85 as FLOAT) as para_1,
-- CAST(string_field_86 as FLOAT) as para_2,
-- CAST(string_field_87 as FLOAT) as brs1,
-- CAST(string_field_88 as FLOAT) as brs2,
-- CAST(string_field_89 as FLOAT) as prod1,
-- CAST(string_field_90 as FLOAT) as prod2,
-- CAST(string_field_91 as FLOAT) as flightlessness,
-- CAST(string_field_92 as FLOAT) as mig,
-- CAST(string_field_93 as FLOAT) as alt,
-- CAST(string_field_94 as FLOAT) as irreg,
-- CAST(string_field_95 as FLOAT) as disp,
-- CAST(string_field_96 as FLOAT) as sed, 
FROM `mackenzie-engenharia-dados.birdbase_bronze.birdbase_data` LIMIT 1000