birdbase:
  outputs:
    dev:
      dataset: birdbase_silver_homolog
      fixed_retries: 1
      location: US
      method: service-account
      keyfile: /var/www/birdbase/keys/mackenzie-engenharia-dados-dac95f889d36.json
      priority: batch
      project: mackenzie-engenharia-dados
      threads: 20
      timeout_seconds: 800
      type: bigquery
    prod:
      dataset:  birdbase_silver
      fixed_retries: 1
      location: US
      method: service-account
      keyfile: /var/www/birdbase/keys/mackenzie-engenharia-dados-dac95f889d36.json
      priority: batch
      project: mackenzie-engenharia-dados
      threads: 20
      timeout_seconds: 800
      type: bigquery
  target: prod