-- dbt run -select dim_reino_biogeografico
{{
  config(
	materialized='table',
	unique_key='sgk_reino_biogeografico',
	tags=['birdbase', 'dim']
  )
}}

WITH tbl_base AS (
    SELECT 'A' AS sgk_reino_biogeografico, 'A' AS tp_reino_biogeografico, 'Australiano' AS nm_portugues
    UNION ALL SELECT 'C', 'C', 'Cosmopolita'
    UNION ALL SELECT 'E', 'E', 'Hemisfério Oriental'
    UNION ALL SELECT 'F', 'F', 'Afrotropical'
    UNION ALL SELECT 'I', 'I', 'Indomalaio'
    UNION ALL SELECT 'L', 'L', 'Neotropical'
    UNION ALL SELECT 'M', 'M', 'Madagascar e Ilhas'
    UNION ALL SELECT 'N', 'N', 'Neártico'
    UNION ALL SELECT 'O', 'O', 'Oceania'
    UNION ALL SELECT 'P', 'P', 'Paleártico'
    UNION ALL SELECT 'S', 'S', 'Polo Sul'
    UNION ALL SELECT 'W', 'W', 'Wallacea'
    UNION ALL SELECT 'Z', 'Z', 'Nova Zelândia e Ilhas'

    -- Combinações compostas
    UNION ALL SELECT 'LN', 'LN', 'Neotropical, Neártico'
    UNION ALL SELECT 'AW', 'AW', 'Australiano, Wallacea'
    UNION ALL SELECT 'AIW', 'AIW', 'Australiano, Indomalaio, Wallacea'
    UNION ALL SELECT 'IP', 'IP', 'Indomalaio, Paleártico'
    UNION ALL SELECT 'FM', 'FM', 'Afrotropical, Madagascar e Ilhas'
    UNION ALL SELECT 'NP', 'NP', 'Neártico, Paleártico'
    UNION ALL SELECT 'AZNP', 'AZNP', 'Australiano, Nova Zelândia e Ilhas, Neártico, Paleártico'
    UNION ALL SELECT 'AZ', 'AZ', 'Australiano, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'PI', 'PI', 'Paleártico, Indomalaio'
    UNION ALL SELECT 'AIFW', 'AIFW', 'Australiano, Indomalaio, Afrotropical, Wallacea'
    UNION ALL SELECT 'EN', 'EN', 'Hemisfério Oriental, Neártico'
    UNION ALL SELECT 'IW', 'IW', 'Indomalaio, Wallacea'
    UNION ALL SELECT 'FP', 'FP', 'Afrotropical, Paleártico'
    UNION ALL SELECT 'FL', 'FL', 'Afrotropical, Neotropical'
    UNION ALL SELECT 'FPI', 'FPI', 'Afrotropical, Paleártico, Indomalaio'
    UNION ALL SELECT 'PIN', 'PIN', 'Paleártico, Indomalaio, Neártico'
    UNION ALL SELECT 'NPI', 'NPI', 'Neártico, Paleártico, Indomalaio'
    UNION ALL SELECT 'NL', 'NL', 'Neártico, Neotropical'
    UNION ALL SELECT 'AO', 'AO', 'Australiano, Oceania'
    UNION ALL SELECT 'EIAZ', 'EIAZ', 'Hemisfério Oriental, Indomalaio, Australiano, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'FI', 'FI', 'Afrotropical, Indomalaio'
    UNION ALL SELECT 'OZ', 'OZ', 'Oceania, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'AWZ', 'AWZ', 'Australiano, Wallacea, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'AI', 'AI', 'Australiano, Indomalaio'
    UNION ALL SELECT 'PIAZ', 'PIAZ', 'Paleártico, Indomalaio, Australiano, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'AIWZ', 'AIWZ', 'Australiano, Indomalaio, Wallacea, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'EAIFZ', 'EAIFZ', 'Hemisfério Oriental, Australiano, Indomalaio, Afrotropical, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'EFAIZM', 'EFAIZM', 'Hemisfério Oriental, Afrotropical, Australiano, Indomalaio, Nova Zelândia e Ilhas, Madagascar e Ilhas'
    UNION ALL SELECT 'IA', 'IA', 'Indomalaio, Australiano'
    UNION ALL SELECT 'EAZFIM', 'EAZFIM', 'Hemisfério Oriental, Australiano, Nova Zelândia e Ilhas, Afrotropical, Indomalaio, Madagascar e Ilhas'
    UNION ALL SELECT 'AOZ', 'AOZ', 'Australiano, Oceania, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'EAZ', 'EAZ', 'Hemisfério Oriental, Australiano, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'LS', 'LS', 'Neotropical, Polo Sul'
    UNION ALL SELECT 'CZ', 'CZ', 'Cosmopolita, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'AIZ', 'AIZ', 'Australiano, Indomalaio, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'FIPA', 'FIPA', 'Afrotropical, Indomalaio, Paleártico, Australiano'
    UNION ALL SELECT 'EZ', 'EZ', 'Hemisfério Oriental, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'NOZ', 'NOZ', 'Neártico, Oceania, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'OA', 'OA', 'Oceania, Australiano'
    UNION ALL SELECT 'ZS', 'ZS', 'Nova Zelândia e Ilhas, Polo Sul'
    UNION ALL SELECT 'SZ', 'SZ', 'Polo Sul, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'CZAS', 'CZAS', 'Cosmopolita, Nova Zelândia e Ilhas, Australiano, Polo Sul'
    UNION ALL SELECT 'PN', 'PN', 'Paleártico, Neártico'
    UNION ALL SELECT 'LNP', 'LNP', 'Neotropical, Neártico, Paleártico'
    UNION ALL SELECT 'CAZ', 'CAZ', 'Cosmopolita, Australiano, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'IO', 'IO', 'Indomalaio, Oceania'
    UNION ALL SELECT 'SF', 'SF', 'Polo Sul, Afrotropical'
    UNION ALL SELECT 'OSZ', 'OSZ', 'Oceania, Polo Sul, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'OP', 'OP', 'Oceania, Paleártico'
    UNION ALL SELECT 'ASZ', 'ASZ', 'Australiano, Polo Sul, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'SLNFP', 'SLNFP', 'Polo Sul, Neotropical, Neártico, Afrotropical, Paleártico'
    UNION ALL SELECT 'LO', 'LO', 'Neotropical, Oceania'
    UNION ALL SELECT 'NPLFS', 'NPLFS', 'Neártico, Paleártico, Neotropical, Afrotropical, Polo Sul'
    UNION ALL SELECT 'OAIFM', 'OAIFM', 'Oceania, Australiano, Indomalaio, Afrotropical, Madagascar e Ilhas'
    UNION ALL SELECT 'PO', 'PO', 'Paleártico, Oceania'
    UNION ALL SELECT 'OL', 'OL', 'Oceania, Neotropical'
    UNION ALL SELECT 'NZPFIA', 'NZPFIA', 'Nova Zelândia e Ilhas, Paleártico, Afrotropical, Indomalaio, Australiano'
    UNION ALL SELECT 'IPZ', 'IPZ', 'Indomalaio, Paleártico, Nova Zelândia e Ilhas'
    UNION ALL SELECT 'FMPIAO', 'FMPIAO', 'Afrotropical, Madagascar e Ilhas, Paleártico, Indomalaio, Australiano, Oceania'
    UNION ALL SELECT 'AIP', 'AIP', 'Australiano, Indomalaio, Paleártico'
    UNION ALL SELECT 'FMP', 'FMP', 'Afrotropical, Madagascar e Ilhas, Paleártico'
    UNION ALL SELECT 'PA', 'PA', 'Paleártico, Australiano'
    UNION ALL SELECT 'EF', 'EF', 'Hemisfério Oriental, Afrotropical'
    UNION ALL SELECT 'IPW', 'IPW', 'Indomalaio, Paleártico, Wallacea'
    UNION ALL SELECT 'IAP', 'IAP', 'Indomalaio, Australiano, Paleártico'
    UNION ALL SELECT 'PF', 'PF', 'Paleártico, Afrotropical'
    UNION ALL SELECT 'IPA', 'IPA', 'Indomalaio, Paleártico, Australiano'
    UNION ALL SELECT 'PIW', 'PIW', 'Paleártico, Indomalaio, Wallacea'
    UNION ALL SELECT 'IPNW', 'IPNW', 'Indomalaio, Paleártico, Neártico, Wallacea'
    UNION ALL SELECT 'PFI', 'PFI', 'Paleártico, Afrotropical, Indomalaio'
    UNION ALL SELECT 'PM', 'PM', 'Paleártico, Madagascar e Ilhas'
    UNION ALL SELECT 'IFP', 'IFP', 'Indomalaio, Afrotropical, Paleártico'
    UNION ALL SELECT 'WA', 'WA', 'Wallacea, Australiano'
    UNION ALL SELECT 'AOW', 'AOW', 'Australiano, Oceania, Wallacea'
)
SELECT * FROM tbl_base
